### ISSUE TITLE
Consider using another BRKGA implementation

### ISSUE THREAD

**Issue by dbofmmbt** [victorftsilva/trade-optimizer#2]
Hello, Victor! I've been working on an optimization framework as a side project and I see that you implemented the BRKGA metaheuristic here. [Optimum](https://github.com/dbofmmbt/optimum) has a BRKGA implementation which may be more efficient, although I decided not to introduce parallelism in this first moment.

Optimum is a WIP, but I think the BRKGA implementation is fairly self-contained and probably won't change for a while. If I find time, maybe I'll do this experiment myself, but if you get interested, let me know. It would be the first use of optimum by another person, and I would appreciate feedback regards the documentation and API.

**Comment by victorftsilva** [comment]
Thanks for sharing @dbofmmbt , i will most definelly checkout Optimum, but currently parallelism in indispensible for trade-optimizer, the runtime execution is already to long depending on the parameters of BRKGA, even running with a powerfull CPU. I had considered using a external package for the implementation, whitch would most definelly implement it in a better way than on trade-optimizer, probably the case for Optimum, but most often the lack of build-in parallelism was a deal breaker.

Maybe in a version 2, i can give it a shot of a PR with Optimum with more updates. 

Thanks again for the contribution
